#!/usr/bin/env bun
// Renders public/resume.pdf from src/data/resume.en.json via Typst.
// Resolves a `typst` binary from PATH, else downloads the official release
// binary (Linux x86_64 only) into node_modules/.cache/typst/.
// Run via `bun scripts/render-pdf.ts` — wired as the `prebuild` script.

import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, cpSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { formatDate } from './date-format';
import type { Resume, ResumeEducation } from '../src/data/resume';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CACHE_DIR = join(ROOT, 'node_modules', '.cache', 'typst');

const resume: Resume = JSON.parse(readFileSync(join(ROOT, 'src/data/resume.en.json'), 'utf-8'));

function workPeriod(job: { startDate: string; endDate?: string }): string {
  return `${formatDate(job.startDate)} – ${job.endDate ? formatDate(job.endDate) : 'Present'}`;
}

function eduPeriod(edu: ResumeEducation): string {
  const start = formatDate(edu.startDate);
  const end = edu.endDate ? formatDate(edu.endDate) : 'Present';
  const status = edu.status ? ` (${edu.status})` : '';
  return `${start} – ${end}${status}`;
}

// Strips scheme + trailing slash for display text, e.g. "https://github.com/x/" -> "github.com/x".
// The full URL is kept separately and used as the #link() target, so it's still clickable.
function stripUrl(url: string): string {
  return url.replace(/^https?:\/\//, '').replace(/\/+$/, '');
}

// Typst string literals only need \ and " escaped; interpolating a string
// value (#var) in markup inserts it as literal text, so no markup-char
// escaping (*, _, #, ...) is needed.
function typstStr(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\s+/g, ' ')}"`;
}

function typstOpt(s: string | undefined): string {
  return s ? typstStr(s) : 'none';
}

function typstArr(items: string[]): string {
  if (items.length === 0) return '()';
  // Typst parses "(x)" as the bare value x, not a 1-item array — needs a trailing comma.
  if (items.length === 1) return `(${typstStr(items[0])},)`;
  return `(${items.map(typstStr).join(', ')})`;
}

// Wraps a list of already-formatted Typst dict entries into a Typst array —
// () for an empty list, else a trailing-comma'd, newline-joined block (Typst
// needs the trailing comma so a single-entry list stays an array, not the
// bare value it parses "(x)" as without one).
function typstDictArray(entries: string[]): string {
  return entries.length === 0 ? '()' : `(\n${entries.join(',\n')},\n)`;
}

const { basics, work, education, awards, skills } = resume;

// Contact line, in order: location city, email, every profile, then the website —
// each entry keeps its full URL as the #link() target but shows stripped display text.
const contactEntries: { text: string; link?: string }[] = [];
if (basics.location?.city) contactEntries.push({ text: basics.location.city });
contactEntries.push({ text: basics.email, link: `mailto:${basics.email}` });
for (const p of basics.profiles) contactEntries.push({ text: stripUrl(p.url), link: p.url });
if (basics.url) contactEntries.push({ text: stripUrl(basics.url), link: basics.url });

const contactItemsTypst = `(${contactEntries
  .map((i) => `(text: ${typstStr(i.text)}, link: ${typstOpt(i.link)})`)
  .join(', ')})`;

// ponytail: character-count heuristic to pick a contact-line size that avoids wrapping,
// not real text measurement. Swap for a Typst `context` layout query if it ever misjudges.
const contactPlainLength = contactEntries.map((i) => i.text).join(' · ').length;
const contactSize = contactPlainLength > 90 ? '9pt' : '9.5pt';

const workTypst = typstDictArray(
  work.map(
    (job) => `  (
    position: ${typstStr(job.position)},
    company: ${typstStr(job.name)},
    company_url: ${typstOpt(job.url)},
    location: ${typstOpt(job.location)},
    period: ${typstStr(workPeriod(job))},
    highlights: ${typstArr(job.highlights)},
  )`
  )
);

const skillsTypst = typstDictArray(
  skills.map((s) => `  (name: ${typstStr(s.name)}, keywords: ${typstArr(s.keywords)})`)
);

const educationTypst = typstDictArray(
  education.map(
    (e) => `  (
    institution: ${typstStr(e.institution)},
    degree: ${typstStr(`${e.studyType}, ${e.area}`)},
    period: ${typstStr(eduPeriod(e))},
  )`
  )
);

const awardsTypst = typstDictArray(
  awards.map(
    (a) => `  (
    title: ${typstStr(a.title)},
    awarder: ${typstStr(a.awarder)},
    date: ${typstStr(a.date)},
    summary: ${typstOpt(a.summary)},
  )`
  )
);

const typstSource = `// Generated by scripts/render-pdf.ts from src/data/resume.en.json — do not edit by hand.
#let name = ${typstStr(basics.name)}
#let label = ${typstStr(basics.label)}
#let contact_items = ${contactItemsTypst}
#let summary = ${typstStr(basics.summary)}
#let work = ${workTypst}
#let skills = ${skillsTypst}
#let education = ${educationTypst}
#let awards = ${awardsTypst}

#set document(title: name + " — " + label, author: name)
#set page(margin: 1.7cm)
#set text(font: "New Computer Modern", size: 10pt)
#set par(justify: true, leading: 0.58em)

#let section(title) = {
  v(12pt)
  text(size: 10.5pt, weight: "bold", tracking: 0.5pt)[#upper(title)]
  v(2pt)
  line(length: 100%, stroke: 0.4pt + gray)
  v(6pt)
}

#align(center)[
  #text(size: 21pt, weight: "bold")[#name] \\
  #text(size: 11pt)[#label] \\
  #v(3pt)
  #set par(justify: false)
  #text(size: ${contactSize})[
    #for (i, item) in contact_items.enumerate() [
      #if item.link != none [#link(item.link)[#item.text]] else [#item.text]#if i < contact_items.len() - 1 [ #h(3pt)·#h(3pt) ]
    ]
  ]
]

#section("Summary")
#summary

#section("Experience")
#set list(indent: 0pt, body-indent: 0.85em, spacing: 0.35em)
#for job in work [
  #grid(
    columns: (1fr, auto),
    text(weight: "bold")[#job.position — #if job.company_url != none [#link(job.company_url)[#job.company]] else [#job.company]],
    text(style: "italic", size: 9pt)[#job.period],
  )
  #if job.location != none [
    #text(size: 9pt, style: "italic")[#job.location]
  ]
  #text(size: 9.8pt)[
    #for h in job.highlights [
      - #h
    ]
  ]
  #v(4pt)
]

#section("Skills")
#for s in skills [
  #text(weight: "bold")[#s.name:] #s.keywords.join(", ") \\
]

#section("Education")
#for e in education [
  #grid(
    columns: (1fr, auto),
    text(weight: "bold")[#e.institution],
    text(style: "italic", size: 9pt)[#e.period],
  )
  #e.degree
  #v(4pt)
]

#section("Awards")
#for a in awards [
  #text(weight: "bold")[#a.title] — #a.awarder (#a.date)
  #if a.summary != none [
    \\ #text(size: 9pt)[#a.summary]
  ]
  #v(4pt)
]
`;

function resolveTypstBinary(): string {
  try {
    execFileSync('typst', ['--version'], { stdio: 'ignore' });
    return 'typst';
  } catch {
    // not on PATH — fall through to cache/download below
  }

  const cached = join(CACHE_DIR, 'typst');
  if (existsSync(cached)) return cached;

  if (process.platform !== 'linux' || process.arch !== 'x64') {
    throw new Error(
      `No 'typst' binary on PATH, and no prebuilt download configured for ${process.platform}/${process.arch} ` +
        `(only Linux x86_64 auto-downloads). Install typst manually — https://github.com/typst/typst/releases — and re-run.`
    );
  }

  console.log('typst not found on PATH — downloading release binary for x86_64-unknown-linux-musl...');
  mkdirSync(CACHE_DIR, { recursive: true });

  const target = 'x86_64-unknown-linux-musl';
  const assetName = `typst-${target}.tar.xz`;
  let downloadUrl: string;
  try {
    const release = execFileSync('curl', [
      '-sL',
      '--max-time',
      '15',
      'https://api.github.com/repos/typst/typst/releases/latest',
    ]).toString();
    const match = new RegExp(`"browser_download_url":\\s*"([^"]*${assetName})"`).exec(release);
    if (!match) throw new Error(`asset ${assetName} not found in latest release response`);
    downloadUrl = match[1];
  } catch (err) {
    throw new Error(
      `Could not resolve typst download URL from GitHub releases (network issue or API change): ${(err as Error).message}`
    );
  }

  const tarPath = join(CACHE_DIR, assetName);
  try {
    execFileSync('curl', ['-sL', '--max-time', '120', '-o', tarPath, downloadUrl]);
    execFileSync('tar', ['-xJf', tarPath, '-C', CACHE_DIR]);
  } catch (err) {
    throw new Error(`Failed to download/extract typst binary: ${(err as Error).message}`);
  }

  const extractedDir = join(CACHE_DIR, `typst-${target}`);
  const extracted = join(extractedDir, 'typst');
  if (!existsSync(extracted)) {
    throw new Error(`Expected typst binary at ${extracted} after extraction, but it's missing.`);
  }
  cpSync(extracted, cached);
  chmodSync(cached, 0o755);
  rmSync(tarPath, { force: true });
  rmSync(extractedDir, { recursive: true, force: true });
  return cached;
}

const typstBin = resolveTypstBinary();

mkdirSync(CACHE_DIR, { recursive: true });
const srcPath = join(CACHE_DIR, 'resume.typ');
writeFileSync(srcPath, typstSource, 'utf-8');

const outPath = join(ROOT, 'public', 'resume.pdf');
execFileSync(typstBin, ['compile', srcPath, outPath], { stdio: 'inherit' });
console.log(`Wrote ${outPath}`);
